// Single import point for the icons used across the app, so the set stays curated.
export {
    ArrowDownWideNarrow,
    Award,
    BadgeCheck,
    BarChart3,
    BookOpen,
    Briefcase,
    Check,
    ChevronDown,
    ChevronRight,
    Copy,
    Download,
    Eye,
    EyeOff,
    FolderGit2,
    GripVertical,
    GraduationCap,
    HeartHandshake,
    Languages,
    Layers,
    Library,
    Loader2,
    Lock,
    LogOut,
    Menu,
    PanelRight,
    PenLine,
    Plus,
    Search,
    SlidersHorizontal,
    Sparkles,
    Target,
    Trash2,
    Upload,
    User,
    Wand2,
    Wrench,
    X,
    type LucideIcon,
} from "lucide-react";
